@apiUrl = {{$dotenv API_URL}}
@token = {{$dotenv TOKEN}}

### GET Node

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

query Node($id: ID!) {
  node(id: $id) {
    id
    ... on Org {
      name
      _ct
      _md
    }
    ... on User {
      name
      _ct
      _md
    }
  }
}

{
  "id": "eyJwayI6eyJTIjoiT1JHIzdhY2FmMmU4LTY4ZDgtNGM4Yi1iYTM0LTlhOWM1NTZiODk1YSJ9LCJzayI6eyJTIjoiT1JHIzdhY2FmMmU4LTY4ZDgtNGM4Yi1iYTM0LTlhOWM1NTZiODk1YSJ9fQ=="
}

### PUT Building

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

mutation PutBuilding($name: String!) {
  putBuilding(name: $name) {
    id
    name
  }
}

{
"name": "bldg-4"
}

### GET Buildings

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

query GetBuildings($first: Int, $after: String, $last: Int, $before: String) {
  getBuildings(first: $first, after: $after, last: $last, before: $before) {
    edges {
      cursor
      node { id, name }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    ctx
  }
}

{
  "first": 20,
  "afterz": "eyJHU0kxcGsiOnsiUyI6IkJVSUxESU5HIn0sInNrIjp7IlMiOiJCVUlMRElORyMwMUcxVzFBQjhFTUZKME1SNFQwWTlCQkVIRiJ9LCJHU0kxc2siOnsiUyI6IkJVSUxESU5HIzAxRzFXMUFCOEVNRkowTVI0VDBZOUJCRUhGIn0sInBrIjp7IlMiOiJCVUlMRElORyMwMUcxVzFBQjhFTUZKME1SNFQwWTlCQkVIRiJ9fQ=="
}

### GET Org (uid)

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

query GetOrg($uid: ID!) {
  getOrg(uid: $uid) {
    id
    name
    uid
  }
}

{
  "uid": "4179c7a3-2d4a-4696-8a09-c05fd521d92d"
}

### GET Org

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

query ($id: ID!) {
  org(id: $id) {
    id
    name
    uid
  }
}

{
  "id": "eyJHU0kxcGsiOnsiTSI6eyJTIjp7IlMiOiJPUkcifX19LCJzayI6eyJNIjp7IlMiOnsiUyI6Ik9SRyMwMWYzMzFkNC0zYTk2LTQ4NTQtOTNmMS1iODU0NzBkZjQxZDEifX19LCJHU0kxc2siOnsiTSI6eyJTIjp7IlMiOiJPUkcjMDFmMzMxZDQtM2E5Ni00ODU0LTkzZjEtYjg1NDcwZGY0MWQxIn19fSwicGsiOnsiTSI6eyJTIjp7IlMiOiJPUkcjMDFmMzMxZDQtM2E5Ni00ODU0LTkzZjEtYjg1NDcwZGY0MWQxIn19fX0="
}

### GET Orgs

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

query GetOrgs($first: Int, $after: String, $last: Int, $before: String) {
  getOrgs(first: $first, after: $after, last: $last, before: $before) {
    edges {
      cursor
      node { name }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}

{
  "first": 2
}

### Create Org

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

mutation ($name: String!) {
  createOrg(name: $name) {
    id
    name
  }
}

{
"name": "org-6"
}

### Create User

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

mutation CreateUser($orgId: ID!, $name: String!) {
  createUser(orgId: $orgId, name: $name) {
    id
    uid
    pid
    name
    _ct
    _md
  }
}

{
"orgId": "7acaf2e8-68d8-4c8b-ba34-9a9c556b895a",
"name": "user-9-2"
}

### Create Device

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

mutation ($name: String!) {
  createDevice(name: $name) {
    id
    name
    _ct
    _md
  }
}

{
"name": "device-1"
}

### Create Sensor

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

mutation ($deviceId: ID!, $name: String!) {
  createSensor(deviceId: $deviceId, name: $name) {
    id
    pid
    name
    _ct
    _md
  }
}

{
  "name": "sensor-0-1",
  "deviceId": "9220af28-8363-45b1-96f7-5daf69dd666f"
}

### List Device Sensors

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

query ($deviceId: ID!, $limit: Int, $nextToken: String) {
  getDeviceSensors(
    deviceId: $deviceId
    limit: $limit
    nextToken: $nextToken
  ) {
    items {
      id
      pid
      name
      _ct
      _md
    }
    nextToken
  }
}

{
  "limit": 10,
  "deviceId": "9220af28-8363-45b1-96f7-5daf69dd666f",
  "nextToken": null
}

### List Devices

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

query {
  listDevices {
    id
    name
    _ct
    _md
  }
}

### GET Device

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

query ($id: ID!, $limit: Int) {
  getDevice(id: $id, limit: $limit) {
    id
    name
    _ct
    _md
  }
}

{
  "id": "9220af28-8363-45b1-96f7-5daf69dd666f",
  "limit": 10
}

### GET Device (Lambda Resolver)

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

query ($id: ID!) {
  getDeviceFn(id: $id) {
    id
    name
    _ct
    _md
  }
}

{
  "id": "9220af28-8363-45b1-96f7-5daf69dd666f"
}
