@apiUrl = {{$dotenv API_URL}}
@token = {{$dotenv TOKEN}}

### GET Node

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

query Node($id: ID!) {
  node(id: $id) {
    id
    ... on Org {
      name
      _ct
      _md
    }
    ... on User {
      name
      _ct
      _md
    }
  }
}

{
  "id": "eyJwayI6eyJTIjoiT1JHIzdhY2FmMmU4LTY4ZDgtNGM4Yi1iYTM0LTlhOWM1NTZiODk1YSJ9LCJzayI6eyJTIjoiT1JHIzdhY2FmMmU4LTY4ZDgtNGM4Yi1iYTM0LTlhOWM1NTZiODk1YSJ9fQ=="
}

### GET Org

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

query ($id: ID!) {
  org(id: $id) {
    id
    name
    _ct
    _md
    users(first: 2, after: "eyJzayI6eyJTIjoiVVNFUiMwMUcwWjZUQU5IUzM1SEtXMDZXMVZSRTdENSJ9LCJwayI6eyJTIjoiT1JHIzdhY2FmMmU4LTY4ZDgtNGM4Yi1iYTM0LTlhOWM1NTZiODk1YSJ9fQ==") {
      edges {
        cursor
        node { name }
      }
      pageInfo {
        hasNextPage
        startCursor
      }
    }
  }
}

{
  "id": "eyJwayI6eyJTIjoiT1JHIzdhY2FmMmU4LTY4ZDgtNGM4Yi1iYTM0LTlhOWM1NTZiODk1YSJ9LCJzayI6eyJTIjoiT1JHIzdhY2FmMmU4LTY4ZDgtNGM4Yi1iYTM0LTlhOWM1NTZiODk1YSJ9fQ=="
}

### Create Org

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

mutation ($name: String!) {
  createOrg(name: $name) {
    id
    name
    _ct
    _md
  }
}

{
"name": "org-9"
}

### Create User

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

mutation CreateUser($orgId: ID!, $name: String!) {
  createUser(orgId: $orgId, name: $name) {
    id
    uid
    pid
    name
    _ct
    _md
  }
}

{
"orgId": "7acaf2e8-68d8-4c8b-ba34-9a9c556b895a",
"name": "user-9-2"
}

### Create Device

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

mutation ($name: String!) {
  createDevice(name: $name) {
    id
    name
    _ct
    _md
  }
}

{
"name": "device-1"
}

### Create Sensor

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

mutation ($deviceId: ID!, $name: String!) {
  createSensor(deviceId: $deviceId, name: $name) {
    id
    pid
    name
    _ct
    _md
  }
}

{
  "name": "sensor-0-1",
  "deviceId": "9220af28-8363-45b1-96f7-5daf69dd666f"
}

### List Device Sensors

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

query ($deviceId: ID!, $limit: Int, $nextToken: String) {
  getDeviceSensors(
    deviceId: $deviceId
    limit: $limit
    nextToken: $nextToken
  ) {
    items {
      id
      pid
      name
      _ct
      _md
    }
    nextToken
  }
}

{
  "limit": 10,
  "deviceId": "9220af28-8363-45b1-96f7-5daf69dd666f",
  "nextToken": null
}

### List Devices

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

query {
  listDevices {
    id
    name
    _ct
    _md
  }
}

### GET Device

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

query ($id: ID!, $limit: Int) {
  getDevice(id: $id, limit: $limit) {
    id
    name
    _ct
    _md
  }
}

{
  "id": "9220af28-8363-45b1-96f7-5daf69dd666f",
  "limit": 10
}

### GET Device (Lambda Resolver)

POST {{apiUrl}}
Content-Type: application/json
Authorization: {{token}}
X-REQUEST-TYPE: GraphQL

query ($id: ID!) {
  getDeviceFn(id: $id) {
    id
    name
    _ct
    _md
  }
}

{
  "id": "9220af28-8363-45b1-96f7-5daf69dd666f"
}
